# Specify Base Image
FROM node:18-alpine
 
# Work Directory
WORKDIR /usr/app

#Copy the required file into the container
COPY ./ ./

COPY package.json .

# Install Dependencies
RUN npm install
 
# Startup Command
CMD ["npm", "run","serve"]
